name: tasks
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectivity: ^3.0.6
  dio: ^4.0.4
  eva_icons_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.1
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^1.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  path_provider: ^2.0.8
  riverpod: ^1.0.0
  shared_preferences: ^2.0.9

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  hive_generator: ^1.1.1
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-italic.ttf
          style: italic
